version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    environment:
      - USING_DOCKER=True
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env-file:
      - .env.dev.db

volumes:
  postgres_data:
